# Generated by Django 4.0.1 on 2022-02-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesdepenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='owner',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='owner',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
